---
- name: Init Swarm Master
  hosts: masters
  become: true
  gather_facts: False
  remote_user: ec2-user
  tasks:
    - name: Swarm Init
      # command: sudo usermod -aG docker {{remote_user}}
      command: docker swarm init --advertise-addr {{ inventory_hostname }}

    - name: Get Worker Token
      command: docker swarm join-token worker -q
      register: worker_token

    - name: Show Worker Token
      debug: var=worker_token.stdout

    - name: Master Token
      command: docker swarm join-token manager -q
      register: master_token

    - name: Show Master Token
      debug: var=master_token.stdout
