language: python
python: 3.7
dist: xenial
sudo: true

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -e .
# command to run tests
script:
  - pytest

branches:
    only:
        - dev
        - master
        - issue/22c5c19

notifications:
  slack:
    rooms:
      - soundright:S3MSovZcyt8SLApWT8wmSYW5#development
