FROM alpine:3.7

ENV FLASK_ENV development

COPY ./voicereader /app/voicereader
COPY config.json /app
COPY config.development.json /app
COPY firebase-adminsdk.json /app
COPY run.py /app
WORKDIR /app

RUN apk add -U --no-cache gcc build-base \
    python3-dev libffi-dev openssl-dev \
    && pip3 install -r voicereader/requirements.txt

EXPOSE 5000

CMD [ "python3", "run.py" ]
