version: "3.0"

services:
  nginx:
    image: nginx:1.13.5
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  api:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - app-resource-volume:/app/upload

  mongodb:
    image: mongo:4.0.4
    volumes:
      - data-volume:/data/db
    ports:
      - "27017:27017"

volumes:
  app-resource-volume:
  data-volume: