version: "3.0"

services:
  api:
    build: .
    command: python -u run.py
    ports:
      - "5000"
    volumes:
      - .:/app
    links:
      - mongodb
  mongodb:
    image: mongo:4.0.4
    volumes:
      - data-volume:/data/db
    ports:
      - "27017:27017"
  nginx:
    restart: always
    image: nginx:1.13.5
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
volumes:
  data-volume: