version: "3.0"

services:
  api:
    build: .
    command: python -u run.py
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    links:
      - mongodb
  mongodb:
    image: mongo:4.0.4
    volumes:
      - data-volume:/data/db
    ports:
      - "27017:27017"
volumes:
  data-volume: