version: "3.0"

services:
  nginx:
    image: nginx:1.13.5
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    deploy:
      placement:
        constraints: [node.role == manager]
#    links:
#      - api
#    networks:
#      - apinet

  api:
    image: gyuhwankim/voicereader-rest:latest
    deploy:
#      replicas: 2
      restart_policy:
        condition: on-failure
    ports:
      - "5000"
    volumes:
      - app-volume:/app
#    links:
#      - mongodb
#    networks:
#      - apinet

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
#    networks:
#      - apinet

  mongodb:
    image: mongo:4.0.4
    volumes:
      - data-volume:/data/db
    ports:
      - "27017:27017"
    deploy:
      placement:
        constraints: [node.role == manager]
#    networks:
#      - apinet

volumes:
  app-volume:
  data-volume:

#networks:
#  apinet: