version: "3.0"

services:
  nginx:
    image: nginx:1.13.5
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    deploy:
      placement:
        constraints: [node.role == manager]

  api:
    image: gyuhwankim/voicereader-rest:latest
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    ports:
      - "5000"
    volumes:
      - app-resource-volume:/app/upload

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]

  mongodb:
    image: mongo:4.0.4
    volumes:
      - data-volume:/data/db
    ports:
      - "27017:27017"
    deploy:
      placement:
        constraints: [node.role == manager]

volumes:
  app-resource-volume:
  data-volume: