version: "3.2"

services:
  nginx:
    image: nginx:1.13.5-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
    networks:
      - apinet
    depends_on:
      - api
  api:
    image: gyuhwankim/voicereader-rest:latest
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    ports:
      - "5000"
    volumes:
      - app-resource-volume:/app/upload
    networks:
      - apinet
    depends_on:
      - mongodb
    environment:
      - VOICEREADER_API_VERSION
      - MONGO_URI=mongodb://mongodb:27017/VoiceReader
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - apinet
  mongodb:
    image: mvertes/alpine-mongo:4.0.5-0
    volumes:
      - data-volume:/data/db
    ports:
      - "27017"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - apinet

volumes:
  app-resource-volume:
  data-volume:

networks:
  apinet:
    driver: overlay
    attachable: true